spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carpark
    username: root
    password: Haqh1234
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000